# Generated by Django 4.1.7 on 2023-03-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_remove_logo_image_logo_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='logo',
            new_name='image',
        ),
    ]
