# Generated by Django 4.1.7 on 2023-03-09 08:19

from django.db import migrations, models
import file_storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_rename_logo_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to=file_storage.models.logo_upload_path),
        ),
    ]
