# Generated by Django 4.1.7 on 2023-03-08 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logos')),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_address', models.CharField(blank=True, max_length=100)),
                ('company_city', models.CharField(blank=True, max_length=100)),
                ('company_state', models.CharField(blank=True, max_length=100)),
                ('company_zip', models.CharField(blank=True, max_length=100)),
                ('company_phone', models.CharField(blank=True, max_length=100)),
                ('company_email', models.CharField(blank=True, max_length=100)),
                ('company_website', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
