# Generated by Django 4.1.7 on 2023-03-09 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_remove_logo_image_logo_logo'),
        ('users', '0003_settings_company_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_storage.logo'),
        ),
    ]
