# Generated by Django 4.1.7 on 2023-03-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_settings_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
    ]
