# Generated by Django 4.1.7 on 2023-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='company_description',
            field=models.TextField(blank=True),
        ),
    ]
