# Generated by Django 4.1.7 on 2023-03-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_household_size', models.PositiveIntegerField()),
                ('upper_income_bound_1', models.PositiveIntegerField(default=22461)),
                ('upper_income_bound_2', models.PositiveIntegerField(default=27343)),
                ('upper_income_bound_3', models.PositiveIntegerField(default=38184)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=50)),
                ('income_category', models.IntegerField()),
                ('state_subsidy_amount', models.IntegerField()),
                ('energy_certificate_amount', models.IntegerField()),
                ('eligible', models.BooleanField(default=True)),
            ],
        ),
    ]
