# Generated by Django 4.1.7 on 2023-03-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_household_size', models.IntegerField()),
                ('lower_income_limit', models.IntegerField()),
                ('upper_income_limit', models.IntegerField()),
                ('income_category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=50)),
                ('income_category', models.IntegerField()),
                ('state_subsidy_amount', models.IntegerField()),
                ('energy_certificate_amount', models.IntegerField()),
            ],
        ),
    ]
