# Generated by Django 4.1.7 on 2023-03-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomecategory',
            name='income_category',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='lower_income_limit',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='upper_income_limit',
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='upper_income_bound_1',
            field=models.PositiveIntegerField(default=22461),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='upper_income_bound_2',
            field=models.PositiveIntegerField(default=27343),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='upper_income_bound_3',
            field=models.PositiveIntegerField(default=38184),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='tax_household_size',
            field=models.PositiveIntegerField(),
        ),
    ]
