# Generated by Django 4.1.7 on 2023-03-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidies', '0002_remove_incomecategory_income_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='eligible',
            field=models.BooleanField(default=True),
        ),
    ]
