# Generated by Django 4.1.7 on 2023-03-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_built', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('occupancy_status', models.CharField(max_length=50)),
                ('residence_type', models.CharField(max_length=50)),
                ('primary_heating_system', models.CharField(max_length=50)),
                ('secondary_heating_system', models.CharField(max_length=50)),
                ('hot_water_system', models.CharField(max_length=501)),
                ('temperature_setpoint', models.IntegerField(default=19)),
                ('annual_energy_bill', models.IntegerField()),
                ('annual_energy_consumption', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('eligible_for_subsidy', models.BooleanField(default=True)),
                ('tax_household_size', models.IntegerField(default=2)),
                ('tax_income_category', models.IntegerField(default=500000)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(default='air_water_heat_pump', max_length=50)),
                ('project_status', models.CharField(max_length=50)),
                ('hot_water_production', models.BooleanField()),
                ('created_date', models.DateField()),
                ('state_subsidy_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('energy_certificate_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.building')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer'),
        ),
    ]
