# Generated by Django 4.1.7 on 2023-02-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_built', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('number_of_units', models.IntegerField()),
                ('occupancy_status', models.CharField(max_length=50)),
                ('residence_type', models.CharField(max_length=50)),
                ('primary_heating_system', models.CharField(max_length=50)),
                ('secondary_heating_system', models.CharField(max_length=50)),
                ('temperature_setpoint', models.IntegerField()),
                ('annual_energy_bill', models.IntegerField()),
                ('annual_energy_consumption', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RenovationProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_type', models.CharField(max_length=50)),
                ('project_status', models.CharField(max_length=50)),
                ('hot_water_production', models.BooleanField()),
                ('created_date', models.DateField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.building')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer')),
            ],
        ),
    ]
