# Generated by Django 4.1.7 on 2023-03-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercatalog', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='building',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='hot_water_production',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='project_status',
        ),
        migrations.AddField(
            model_name='estimate',
            name='heat_pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usercatalog.userheatpump'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='price',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
