# Generated by Django 4.1.7 on 2023-03-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='annual_energy_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='annual_energy_consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='hot_water_system',
            field=models.CharField(blank=True, max_length=501, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='number_of_floors',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='occupancy_status',
            field=models.CharField(default='owner', max_length=50),
        ),
        migrations.AlterField(
            model_name='building',
            name='primary_heating_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='residence_type',
            field=models.CharField(default='main', max_length=50),
        ),
        migrations.AlterField(
            model_name='building',
            name='secondary_heating_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='square_footage',
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='temperature_setpoint',
            field=models.IntegerField(blank=True, default=19, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_built',
            field=models.IntegerField(blank=True, default=1950, null=True),
        ),
    ]
