# Generated by Django 4.1.7 on 2023-03-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_building_number_of_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='eligible_for_subsidy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_household_size',
            field=models.IntegerField(default=2),
        ),
    ]
