# Generated by Django 4.1.7 on 2023-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_building_annual_energy_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='occupancy_status',
            field=models.CharField(blank=True, default='owner', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='residence_type',
            field=models.CharField(blank=True, default='main', max_length=50, null=True),
        ),
    ]
