# Generated by Django 4.1.7 on 2023-03-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_building_hot_water_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='hot_water_system',
            field=models.CharField(max_length=501),
        ),
        migrations.AlterField(
            model_name='building',
            name='temperature_setpoint',
            field=models.IntegerField(default=19),
        ),
    ]
