# Generated by Django 4.1.7 on 2023-03-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_building_hot_water_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_type', models.CharField(max_length=50)),
                ('project_status', models.CharField(max_length=50)),
                ('hot_water_production', models.BooleanField()),
                ('created_date', models.DateField()),
                ('subsidy', models.DecimalField(decimal_places=2, max_digits=8)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.building')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='RenovationProject',
        ),
    ]
