# Generated by Django 4.1.7 on 2023-03-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_user_customer_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customuser',
            new_name='user',
        ),
    ]
