# Generated by Django 4.1.7 on 2023-03-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_estimate_delete_renovationproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_income',
            field=models.IntegerField(default=0),
        ),
    ]
