# Generated by Django 4.1.7 on 2023-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_customuser_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
