# Generated by Django 4.1.7 on 2023-03-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_customer_tax_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='project_type',
            new_name='equipment_type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_income',
            field=models.IntegerField(default=500000),
        ),
    ]
