# Generated by Django 4.1.7 on 2023-03-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_customer_latitude_customer_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
