# Generated by Django 4.1.7 on 2023-03-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_estimate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='consumption_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
