# Generated by Django 4.1.7 on 2023-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_project_type_estimate_equipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='equipment_type',
            field=models.CharField(default='air_water_heat_pump', max_length=50),
        ),
    ]
