# Generated by Django 4.1.7 on 2023-03-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_estimate_equipment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='subsidy',
            new_name='energy_cerficate_amount',
        ),
        migrations.AddField(
            model_name='estimate',
            name='state_subsidy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
