# Generated by Django 4.1.7 on 2023-03-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_subsidy_estimate_energy_cerficate_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tax_income',
            new_name='tax_income_category',
        ),
    ]
