# Generated by Django 4.1.7 on 2023-03-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rename_tax_income_customer_tax_income_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='energy_cerficate_amount',
            new_name='energy_certificate_amount',
        ),
    ]
