# Generated by Django 4.1.7 on 2023-03-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_area', models.IntegerField()),
                ('window_width', models.IntegerField()),
                ('window_height', models.IntegerField()),
                ('window_type', models.CharField(max_length=50)),
                ('window_size_type', models.CharField(max_length=50)),
                ('window_insulation_u_value', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_area', models.IntegerField()),
                ('wall_height', models.IntegerField()),
                ('wall_insulation_u_value', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_area', models.IntegerField()),
                ('roof_shape', models.CharField(max_length=50)),
                ('roof_height', models.IntegerField()),
                ('roof_type', models.CharField(max_length=50)),
                ('roof_insulation_u_value', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_area', models.IntegerField()),
                ('floor_type', models.CharField(max_length=50)),
                ('floor_insulation_u_value', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.building')),
            ],
        ),
    ]
