# Generated by Django 4.1.7 on 2023-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_insulation_u_value',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roof',
            name='roof_insulation_u_value',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wall',
            name='wall_insulation_u_value',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_insulation_u_value',
            field=models.FloatField(max_length=50),
        ),
    ]
