# Generated by Django 4.1.7 on 2023-03-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0002_alter_floor_floor_insulation_u_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='window',
            old_name='window_type',
            new_name='window_insulation_type',
        ),
    ]
