# Generated by Django 4.1.7 on 2023-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0003_rename_window_type_window_window_insulation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='window_orientation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
