# Generated by Django 4.1.7 on 2023-03-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0004_window_window_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='window_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_insulation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_insulation_u_value',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_size_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
