# Generated by Django 4.1.7 on 2023-03-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_building_occupancy_status_and_more'),
        ('heatloss', '0005_alter_window_window_area_alter_window_window_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiator_type', models.CharField(max_length=50)),
                ('radiator_height', models.IntegerField()),
                ('radiator_width', models.IntegerField()),
                ('radiator_depth', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.building')),
            ],
        ),
    ]
