# Generated by Django 4.1.7 on 2023-03-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0007_rename_radiator_depth_radiator_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiator',
            name='depth',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='height',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='width',
            field=models.FloatField(default=1.5),
        ),
    ]
