# Generated by Django 4.1.7 on 2023-03-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0008_alter_radiator_depth_alter_radiator_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roof',
            name='roof_flat_area',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roof',
            name='roof_perimeter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
