# Generated by Django 4.1.7 on 2023-03-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0009_roof_roof_flat_area_roof_roof_perimeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='roof',
            name='roof_polygon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
