# Generated by Django 4.1.7 on 2023-03-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0010_roof_roof_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='roof_flat_area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='roof',
            name='roof_perimeter',
            field=models.FloatField(),
        ),
    ]
