# Generated by Django 4.1.7 on 2023-03-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0011_alter_roof_roof_flat_area_alter_roof_roof_perimeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='roof_area',
            field=models.FloatField(),
        ),
    ]
