# Generated by Django 4.1.7 on 2023-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0012_alter_roof_roof_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='wall_height',
        ),
        migrations.AddField(
            model_name='wall',
            name='number_of_storeys',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wall',
            name='storey_height',
            field=models.FloatField(default=2.8),
        ),
    ]
