# Generated by Django 4.1.7 on 2023-03-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatloss', '0014_alter_wall_wall_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_area',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_insulation_u_value',
            field=models.FloatField(default='2', max_length=50),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_type',
            field=models.CharField(default='solid-ground', max_length=50),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='type',
            field=models.CharField(default='cast-iron', max_length=50),
        ),
        migrations.AlterField(
            model_name='roof',
            name='roof_area',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='roof',
            name='roof_flat_area',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='roof',
            name='roof_height',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='roof',
            name='roof_insulation_u_value',
            field=models.FloatField(default='2', max_length=50),
        ),
        migrations.AlterField(
            model_name='roof',
            name='roof_perimeter',
            field=models.FloatField(default=40),
        ),
        migrations.AlterField(
            model_name='roof',
            name='roof_shape',
            field=models.CharField(default='hip-roof', max_length=50),
        ),
        migrations.AlterField(
            model_name='roof',
            name='roof_type',
            field=models.CharField(default='lost-attic', max_length=50),
        ),
        migrations.AlterField(
            model_name='wall',
            name='wall_area',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='wall',
            name='wall_insulation_u_value',
            field=models.FloatField(default=2, max_length=50),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_area',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_height',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_insulation_type',
            field=models.CharField(blank=True, default='single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_insulation_u_value',
            field=models.FloatField(blank=True, default=2, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_orientation',
            field=models.CharField(blank=True, default='north', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_size_type',
            field=models.CharField(blank=True, default='medium', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='window_width',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
