# Generated by Django 4.1.7 on 2023-03-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('manufacturer', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('scop', models.FloatField(default=3.5)),
                ('etas', models.FloatField(default=0.8)),
                ('hot_water', models.BooleanField(default=False)),
                ('power_minus_7_55', models.FloatField(default=8.5)),
                ('cop_minus_7_55', models.FloatField(default=3.5)),
                ('power_minus_7_35', models.FloatField(default=8.5)),
                ('cop_minus_7_35', models.FloatField(default=3.5)),
                ('power_7_35', models.FloatField(default=8.5)),
                ('cop_7_35', models.FloatField(default=3.5)),
                ('power_7_55', models.FloatField(default=8.5)),
                ('cop_7_55', models.FloatField(default=3.5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
